package Class;

public class Color {
    public static void main(String a[]){
    int color=3;
    switch(color)
    {
        case 1:
            System.out.println("COLOR IS RED");
        break;

        case 2:
            System.out.println("COLOR IS ROSE");
        break;

        case 3:
            System.out.println("COLOR IS NAVY BLUE");
            break;

            case 4:
        System.out.println("COLOR IS WHITE");
        break;

        default:
            System.out.println("NO OPTIONS FOUND HERE :");

    }

    }
}
